using DTO;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MySql.Data.MySqlClient;

namespace DAO
{
    public class NhomNguoiDungDAO
    {
        public static BindingList<NhomNguoiDungDTO> GetAllNhomNguoiDung()
        {
            BindingList<NhomNguoiDungDTO> list = new BindingList<NhomNguoiDungDTO>();
            string query = @"
                SELECT NND.*, COUNT(ND.ID) AS TongSoNguoi 
                FROM NhomNguoiDung AS NND
                LEFT JOIN NguoiDung AS ND ON ND.IDNhomNguoiDung = NND.ID
                GROUP BY NND.ID
            ";

            DataTable data = DataProvider.Instance.ExecuteQuery(query);

            foreach (DataRow row in data.Rows)
            {
                list.Add(new NhomNguoiDungDTO
                {
                    ID = Convert.ToInt32(row["ID"]),
                    MaNhom = row["MaNhomNguoiDung"].ToString(),
                    TenNhom = row["TenNhomNguoiDung"].ToString(),
                    TongSoNguoi = Convert.ToInt32(row["TongSoNguoi"])
                });
            }
            return list;
        }

        /// <summary>
        /// Adds a new user group by inserting TenNhomNguoiDung; MaNhom is assumed to be generated by DB.
        /// Returns the generated MaNhom (string) or null on failure.
        /// </summary>
        public static string? AddNhomNguoiDung(string tenNhom)
        {
            if (string.IsNullOrWhiteSpace(tenNhom))
                throw new ArgumentException("Ten nhom khong duoc rong", nameof(tenNhom));

            // Insert TenNhomNguoiDung; MaNhom is generated on DB side (trigger/default)
            string insertQuery = "INSERT INTO NhomNguoiDung (TenNhomNguoiDung) VALUES (@Ten);";
            var paramTen = new MySqlParameter("@Ten", tenNhom);

            // Execute insert
            DataProvider.Instance.ExecuteNonQuery(insertQuery, paramTen);

            // Retrieve last insert id
            var idObj = DataProvider.Instance.ExecuteScalar("SELECT LAST_INSERT_ID();");
            if (idObj == null) return null;

            int newId;
            try
            {
                newId = Convert.ToInt32(idObj);
            }
            catch
            {
                return null;
            }

            // Query the newly inserted row to get MaNhom (if generated) and other fields
            string selectQuery = "SELECT * FROM NhomNguoiDung WHERE ID = @Id LIMIT 1";
            var pId = new MySqlParameter("@Id", newId);
            DataTable dt = DataProvider.Instance.ExecuteQuery(selectQuery, pId);
            if (dt.Rows.Count == 0) return null;

            var row = dt.Rows[0];
            var ma = row["MaNhomNguoiDung"]?.ToString();

            return ma;
        }

        public static NhomNguoiDungDTO? GetNhomByMaNhom(string maNhom)
        {
            if (string.IsNullOrWhiteSpace(maNhom)) return null;

            string query = "SELECT * FROM NhomNguoiDung WHERE MaNhomNguoiDung = @Ma LIMIT 1";
            var p = new MySqlParameter("@Ma", maNhom);
            DataTable dt = DataProvider.Instance.ExecuteQuery(query, p);
            if (dt.Rows.Count == 0) return null;

            var row = dt.Rows[0];
            return new NhomNguoiDungDTO
            {
                ID = Convert.ToInt32(row["ID"]),
                MaNhom = row["MaNhomNguoiDung"]?.ToString() ?? string.Empty,
                TenNhom = row["TenNhomNguoiDung"]?.ToString() ?? string.Empty,
                TongSoNguoi = 0
            };
        }

        /// <summary>
        /// Deletes a user group and its associated permissions. Returns true if deletion succeeded.
        /// Will not delete if there are users still assigned to the group.
        /// </summary>
        public static bool DeleteNhomNguoiDung(int groupId)
        {
            if (groupId <= 0) return false;

            // Check if any users belong to this group
            var countObj = DataProvider.Instance.ExecuteScalar("SELECT COUNT(*) FROM NguoiDung WHERE IDNhomNguoiDung = @Id", new MySqlParameter("@Id", groupId));
            int userCount = 0;
            try
            {
                userCount = Convert.ToInt32(countObj);
            }
            catch
            {
                // ignore parsing errors, assume not deletable
                return false;
            }

            if (userCount > 0)
            {
                // Do not delete group when users exist; caller should handle notifying user
                return false;
            }

            // Delete permissions assigned to this group
            DataProvider.Instance.ExecuteNonQuery("DELETE FROM PHANQUYEN WHERE IDNhomNguoiDung = @Id", new MySqlParameter("@Id", groupId));

            // Delete the group itself
            int affected = DataProvider.Instance.ExecuteNonQuery("DELETE FROM NhomNguoiDung WHERE ID = @Id", new MySqlParameter("@Id", groupId));

            return affected > 0;
        }
    }
}
